const {test,expect}=require('@playwright/test');
test.beforeEach(async({request})=>{expect((await request.post('http://127.0.0.1:4311/__test/reset')).ok()).toBe(true);});
const login=async(request,username='audit-admin')=>{
 const r=await request.post('/api/auth/login',{data:{username,password:'local-test-only'}});
 expect(r.status(),await r.text()).toBe(200);
};
test('direct company link, quality filters and saving without a review workflow',async({page,request})=>{
 request = page.request;
 await login(request);
 await page.goto('/chemical?company_id=amt');
 await expect(page.getByText('บริษัท AMT',{exact:false})).toBeVisible();
 await expect(page.getByRole('row').filter({has:page.getByText('Test Missing SDS',{exact:true})})).toBeVisible();
 await expect(page.getByRole('row').filter({has:page.getByText('Test AAB Only',{exact:true})})).toHaveCount(0);
 await page.getByRole('button',{name:'ขาด SDS 1',exact:true}).click();
 await expect(page.getByRole('row').filter({has:page.getByText('Test Missing SDS',{exact:true})})).toBeVisible();
 await expect(page.getByRole('row').filter({has:page.getByText('Test Acetone',{exact:true})})).toHaveCount(0);
 await page.getByRole('button',{name:'ล้างตัวกรอง'}).click();
 await expect(page.getByRole('row').filter({has:page.getByText('Test Acetone',{exact:true})})).toBeVisible();
 await page.getByRole('link',{name:'เพิ่มสารเคมี',exact:true}).click();
 await expect(page.getByRole('heading',{name:'เพิ่มสารเคมีใหม่'})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'หมวดข้อมูลสารเคมี'})).toBeVisible();
 await expect(page.getByLabel('เลือกบริษัท')).toHaveCount(0);
 await page.getByLabel('ชื่อสารเคมี / ชื่อทางการค้า *',{exact:true}).fill('Integration saved to AMT');
 await expect(page.getByRole('heading',{name:'สถานะการตรวจทาน'})).toHaveCount(0);
 const sent=page.waitForRequest(r=>r.url().endsWith('/api/chemical/substances')&&r.method()==='POST');
 await page.getByRole('button',{name:'บันทึกสารเคมี',exact:true}).click();
 expect((await sent).postDataJSON().company_id).toBe('amt');
 await expect(page.getByRole('row').filter({has:page.getByText('Integration saved to AMT',{exact:true})})).toBeVisible();
 const state=await (await request.get('http://127.0.0.1:4311/__test/state')).json();
 const row=state.find(x=>x.name==='Integration saved to AMT');
 expect(row.company_id).toBe('amt');expect(row.review_status).toBe('unreviewed');expect(row.reviewed_by).toBeNull();
 await page.getByRole('link',{name:'แก้ไข Integration saved to AMT',exact:true}).click();
 await expect(page.getByText('ตรวจทานแล้วโดย audit-admin',{exact:true})).toHaveCount(0);
 await page.getByLabel('ชื่อทางเคมี',{exact:true}).fill('Changed after approval');
 await page.getByRole('button',{name:'บันทึกการแก้ไข',exact:true}).click();
 await expect(page.getByRole('row').filter({has:page.getByText('Integration saved to AMT',{exact:true})})).not.toContainText('ยังไม่ตรวจทาน');
 await page.getByLabel('เลือกบริษัท').selectOption('aab');
 await expect(page.getByText('บริษัท AAB',{exact:false})).toBeVisible();
 await expect(page.getByRole('row').filter({has:page.getByText('Test AAB Only',{exact:true})})).toBeVisible();
 await expect(page.getByRole('row').filter({has:page.getByText('Integration saved to AMT',{exact:true})})).toHaveCount(0);
 await expect(page.getByRole('link',{name:'ตารางเก็บร่วม/แยก'}).first()).toHaveAttribute('href','/chemical/compatibility?company_id=aab');
});
test('anonymous, unauthorized company, cross-company area, stale write, and demo partition',async({request})=>{
 const anonymous=await request.get('/api/chemical/substances?company_id=amt');expect(anonymous.status()).toBe(401);
 await login(request,'audit-amt');
 expect((await request.put('/api/chemical/settings',{headers:{origin:'https://unrelated.invalid'},data:{company_id:'amt'}})).status()).toBe(403);
 expect((await request.post('/api/auth/login',{headers:{origin:'https://unrelated.invalid'},data:{username:'audit-admin',password:'local-test-only'}})).status()).toBe(403);
 for(const method of ['get','post']) {
   const r=method==='get'?await request.get('/api/chemical/substances?company_id=aab'):await request.post('/api/chemical/substances',{data:{company_id:'aab',name:'must not save'}});
   expect(r.status()).toBe(403);
 }
 expect((await request.get('/api/chemical/substances?company_id=all')).status()).toBe(403);
 expect((await request.get('/api/chemical/substances/44444444-4444-4444-8444-444444444444')).status()).toBe(404);
 expect((await request.post('/api/chemical/substances',{data:{company_id:'amt',name:'Bad area',storage_area_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'}})).status()).toBe(400);
 expect((await request.post('/api/chemical/substances',{data:{company_id:'amt',name:'Bad SDS',sds_file_path:'aab/123-test.pdf'}})).status()).toBe(400);
 const r=await request.get('/api/chemical/substances/11111111-1111-4111-8111-111111111111');const current=(await r.json()).data;
 expect((await request.put('/api/chemical/substances/'+current.id,{data:{name:'Stale',company_id:'amt',expected_updated_at:'2000-01-01'}})).status()).toBe(409);
 expect((await request.put('/api/chemical/substances/'+current.id,{data:{company_id:'aab',expected_updated_at:current.updated_at}})).status()).toBe(409);
 const actual=(await (await request.get('/api/chemical/substances?company_id=amt')).json()).data;
 expect(actual.some(x=>x.is_demo)).toBe(false);
 const demo=(await (await request.get('/api/chemical/substances?company_id=amt&demo=1')).json()).data;
 expect(demo.map(x=>x.name)).toEqual(['Demo only']);
});
test('emergency settings without review policy, accessible matrices, desktop and mobile layouts',async({page,request})=>{
 request = page.request;
 await login(request);
 await page.goto('/chemical/settings?company_id=amt');
 await expect(page.getByRole('heading',{name:'นโยบายรอบทบทวน SDS'})).toHaveCount(0);
 await page.getByRole('button',{name:'ดับเพลิง 199',exact:true}).click();
 await page.getByRole('button',{name:'บันทึกการตั้งค่า'}).click();
 await expect(page.getByRole('status')).toContainText('บันทึกการตั้งค่า');
 const policy=(await (await request.get('/api/chemical/settings?company_id=amt')).json()).data;
 expect(policy.emergency_contacts.some(c=>c.phone==='199')).toBe(true);
 await page.goto('/chemical/compatibility?company_id=amt');
 await page.getByRole('button',{name:'ตารางอ้างอิง 23 × 23'}).click();
 const cell=page.getByRole('button',{name:/ประเภท 3A กับ 5.1B:/});
 await cell.focus();await expect(cell).toHaveText('×');
 await cell.press('Enter');
 await page.emulateMedia({media:'print'});
 expect(await cell.evaluate(el=>getComputedStyle(el).color)).toBe('rgb(0, 0, 0)');
 expect(await page.locator('.chemical-matrix').evaluate(el=>getComputedStyle(el).maxHeight)).toBe('none');
 await page.emulateMedia({media:'screen'});
 await page.screenshot({path:'test-results/chemical-matrix.png',fullPage:true});
 await page.goto('/chemical?company_id=amt');
 await expect(page.getByText('Test Acetone',{exact:true})).toBeVisible();
 await page.screenshot({path:'test-results/chemical-register-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/chemical-register-mobile.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'เปิดเมนู Chemical'}).click();
 await expect(page.getByLabel('เลือกบริษัท')).toBeVisible();
 await page.getByRole('button',{name:'ปิดเมนู Chemical'}).click();
 await page.goto('/chemical/new?company_id=amt');
 await expect(page.getByRole('heading',{name:'เพิ่มสารเคมีใหม่'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/chemical-form-mobile.png',fullPage:true});
});
test('loading is not empty, failed fetch is recoverable, and fast scope switch ignores old response',async({page,request})=>{
 request = page.request;
 await login(request);
 let release;const gate=new Promise(r=>release=r);
 await page.route('**/api/chemical/substances?company_id=amt*',async route=>{await gate;await route.continue();});
 await page.goto('/chemical?company_id=amt');
 await expect(page.getByText('กำลังโหลด…',{exact:true}).first()).toBeVisible();
 await expect(page.getByText('ยังไม่มีสารเคมีในทะเบียน',{exact:true})).toHaveCount(0);
 await page.getByLabel('เลือกบริษัท').selectOption('aab');
 await expect(page.getByRole('row').filter({has:page.getByText('Test AAB Only',{exact:true})})).toBeVisible();
 release();
 await expect(page.getByRole('row').filter({has:page.getByText('Test Acetone',{exact:true})})).toHaveCount(0);
 await page.unroute('**/api/chemical/substances?company_id=amt*');
 await page.route('**/api/chemical/substances?company_id=amt*',route=>route.fulfill({status:500,json:{error:'ทดสอบโหลดไม่สำเร็จ'}}));
 await page.getByLabel('เลือกบริษัท').selectOption('amt');
 await expect(page.getByText('ทดสอบโหลดไม่สำเร็จ')).toBeVisible();
 await page.unroute('**/api/chemical/substances?company_id=amt*');
 await page.getByRole('button',{name:'ลองใหม่'}).click();
 await expect(page.getByRole('row').filter({has:page.getByText('Test Acetone',{exact:true})})).toBeVisible();
});

test('AI provenance survives reopening without review controls; demo restoration and form scope guard', async({page})=>{
 const request=page.request; await login(request);
 await page.route('**/api/chemical/extract',route=>route.fulfill({json:route.request().method()==='GET'?{available:true}:{data:{name:'AI proposed name',chemical_name:'AI chemical',h_codes:['H225'],ghs_pictograms:['GHS02'],extraction_notes:'Fixture extraction'}}}));
 await page.goto('/chemical/new?company_id=amt');
 await page.getByLabel('ชื่อสารเคมี / ชื่อทางการค้า *',{exact:true}).fill('Human named chemical');
 await page.getByRole('button',{name:'ใส่ลิงก์',exact:true}).click();
 await page.getByLabel('ลิงก์ SDS จากผู้ผลิต').fill('https://example.com/fixture.pdf');
 await page.getByRole('button',{name:'สกัดข้อมูลจาก SDS',exact:false}).click();
 await expect(page.getByLabel('ชื่อทางเคมี',{exact:true})).toHaveValue('AI chemical');
 await expect(page.getByLabel('ชื่อสารเคมี / ชื่อทางการค้า *',{exact:true})).toHaveValue('Human named chemical');
 await page.getByRole('button',{name:'บันทึกสารเคมี',exact:true}).click();
 await expect(page.getByText('Human named chemical',{exact:true})).toBeVisible();
 let row=(await (await request.get('http://127.0.0.1:4311/__test/state')).json()).find(x=>x.name==='Human named chemical');
 expect(row.review_status).toBe('unreviewed');expect(row.ai_filled_fields).toContain('chemical_name');expect(row.ai_filled_fields).not.toContain('name');
 await page.getByRole('link',{name:'แก้ไข Human named chemical',exact:true}).click();
 await expect(page.getByText('มีข้อมูลจาก AI',{exact:false})).toBeVisible();
 await expect(page.getByRole('checkbox',{name:'ฉันตรวจทานข้อมูลกับ SDS ต้นฉบับแล้ว',exact:false})).toHaveCount(0);
 await page.getByRole('button',{name:'บันทึกการแก้ไข',exact:true}).click();
 await expect(page.getByText('Human named chemical',{exact:true})).toBeVisible();
 row=(await (await request.get('/api/chemical/substances/'+row.id)).json()).data;
 expect(row.review_status).toBe('unreviewed');expect(row.ai_filled_fields).toContain('chemical_name');
 const same=await request.put('/api/chemical/substances/'+row.id,{data:{name:row.name,expected_updated_at:row.updated_at}});expect(same.ok()).toBe(true);row=(await same.json()).data;expect(row.review_status).toBe('unreviewed');
 const demo=await request.put('/api/chemical/substances/'+row.id,{data:{demo_action:'mark',expected_updated_at:row.updated_at}});expect(demo.ok()).toBe(true);row=(await demo.json()).data;expect(row.is_demo).toBe(true);
 const restore=await request.put('/api/chemical/substances/'+row.id,{data:{demo_action:'restore',expected_updated_at:row.updated_at}});expect(restore.ok()).toBe(true);expect((await restore.json()).data.review_status).toBe('unreviewed');
 await page.goto('/chemical/new?company_id=amt');
 await expect(page.getByRole('heading',{name:'เพิ่มสารเคมีใหม่'})).toBeVisible();
 await page.evaluate(()=>window.history.pushState(null,'','?company_id=aab'));
 await expect(page.getByText('บริษัทเปลี่ยนไปหรือยังไม่ได้เลือกบริษัท',{exact:false})).toBeVisible();
 await expect(page.getByRole('button',{name:'บันทึกสารเคมี',exact:true})).toHaveCount(0);
});
