"""Check PDFs generated by chemical-label.spec.cjs (requires pypdf)."""
import json
from pathlib import Path
from pypdf import PdfReader
from pypdf.generic import ContentStream

root = Path(__file__).resolve().parent.parent / 'test-results'
manifest = json.loads((root / 'chemical-label-presets.json').read_text(encoding='utf-8'))
for preset, direction, count, width, height in manifest['presets']:
    reader = PdfReader(root / f'chemical-label-{preset}.pdf')
    assert len(reader.pages) == 1, preset
    page = reader.pages[0]
    mm = [float(page.mediabox.width) * 25.4 / 72, float(page.mediabox.height) * 25.4 / 72]
    assert abs(mm[0] - width) < 0.01 and abs(mm[1] - height) < 0.01, (preset, mm)
    operations = ContentStream(page.get_contents(), reader).operations
    assert sum(op == b'Do' for args, op in operations) == count, preset
    links = [a.get_object()['/A']['/URI'] for a in page['/Annots']]
    assert links == [manifest['url']] * count, (preset, links)
    for annotation in page['/Annots']:
        rect = list(map(float, annotation.get_object()['/Rect']))
        left, right = sorted([rect[0], rect[2]])
        bottom, top = sorted([rect[1], rect[3]])
        assert 0 <= left < right <= float(page.mediabox.width)
        assert 0 <= bottom < top <= float(page.mediabox.height)
    # Extract the exact PDF image for an independent QR decoder, without re-rendering it.
    (root / f'embedded-{preset}.png').write_bytes(page.images[0].data)
    print(preset, 'PASS', mm, count, 'labels and clickable SDS links')
